### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by sonro** [allan2/dotenvy#56]
I feel we should create better contributing guidelines for this project. I know its only a small crate, but it would be best if issues were opened before PRs and the current info in the README just says "Contributions and PRs are very welcome!"

I personally think a `CONTRIBUTING.md` file is the way to go, with info on how to pass CI, (testing, clippy, formatting etc). Also updating the README to ask contributors to open an issue first and read the file would be a good idea.

**Comment by allan2** [comment]
Sounds good!

Some thoughts:
- welcoming tone ([Axum](https://github.com/tokio-rs/axum/blob/main/CONTRIBUTING.md) does this well, as does [this user](https://github.com/sonro))
- a suggestion to open issues to solicit feedback before making large changes (paraphrased from [here](https://github.com/tokio-rs/axum/blob/main/CONTRIBUTING.md#pull-requests))
- mention CI (probably not necessary to [write instructions](https://github.com/rust-lang/mdBook/blob/master/CONTRIBUTING.md#formatting-code-with-rustfmt) but it would be good to mention. at least in passing)
- update CHANGELOG
- encourage asking for help (either in issues and/or discussions?). This could be caused by the docs missing something
